### ISSUE TITLE
Deciding what to do with other scripts

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/MiniDrugBank#2]
For now I have included what is required to create the MiniDrugBank molecule set. That is the `pickMolecules.ipynb` jupyter notebook and `DrugBank_atyped.oeb` (input for filtering) and the resulting output for parm@frosst and tripos atom types. 

My question is what should we do with the rest of the [/openforcefield/utilities/filter_molecule_sets/](https://github.com/open-forcefield-group/openforcefield/tree/master/utilities/filter_molecule_sets) directory. Here's a list of what is contained there: 

My suggestion for each file(s) is in **bold**

- [x] Old generations of MiniDrugBank (with generics, which was created before I realized we were including generic parameters in the set) **Remove these I think**
- [x] `DrugBank.sdf` - The sdf file you get when you download DrugBank **Remove this as it isn't used to create MiniDrugBank**
- [x] `DrugBank_updated_*.mol2` - Created with the filter script before we decided to create MiniDrugBank. **Remove since we aren't using them for anything**
- [x] `DrugBank_CHO_atyped.mol2` - molecules with only C,H, and O initially created as an intermediate test set for smarty, but we aren't using it **Remove**
- [x] Other molecule files - aren't documented and I assume were intermediates when we were deciding what to test with smarty/smirky **Remove since we don't have a written record what they were for**
- [x] `filter_molecules.py` - a script I wrote when we were first filtering DrugBank and I thought it was just going to be a matter of removing metals, large molecules, and inappropriate valency. I believe Camila added a functionality to remove molecules that get the generic parm@frosst atom type `gg`. We haven't used this for any molecule set being used on this project (to the best of my knowledge) **It isn't used for MiniDrugBank so I'm not sure what to do with it**
- [x] `elements_exclude.txt` and `remove_smirks.smarts` - example input files for filter_molecules.py **keep if we keep filter_molecules.py**

To clarify - When I say remove, I think we should remove all together, I don't think there is a need to store poorly documented molecules subsets that we aren't using; it is too much to keep track of.

**Comment by bannanc** [comment]
@davidlmobley @camizanette @jchodera your opinion on organization here would be appreciated.

**Comment by davidlmobley** [comment]
@bannanc - I agree with your proposed organization, though I'd like to retain `filter_molecules.py` somewhere, as it's useful enough I've used it on a variety of occasions for different purposes. Maybe that should just be kept in `openforcefield/utilities/filter_molecule_sets`, and the README.md there updated to refer to this repo for DrugBank mini as a larger/more useful molecule set of interest?

**Comment by bannanc** [comment]
I think keeping filter_molecules in `openforcefield/utilities/filter_molecule_sets`, but I don't think we should keep all these basically random molecule files that we don't have a good record of. We could choose one to keep in the filter_molecule_sets directory as an example of how to use that script.

**Comment by davidlmobley** [comment]
Absolutely, yes, @bannanc - I have no interest in the random molecule sets.

**Comment by bannanc** [comment]
Ok, conclusion here incase it wasn't clear, 

filter_molecules and 1 resulting set will stay at openforcefield/utilities/filter_molecules. All others will be removed. 

Only `MiniDrugBank_*.mol2` and `pickMolecules.ipynb` will be moved to this directory.

**Comment by bannanc** [comment]
This can be closed as the primary concern was what to do with files not being moved here.
